"""Add end_date to markets

Revision ID: a1b2c3d4e5f6
Revises: ee390fab20f7
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'ee390fab20f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_markets_end_date'), 'markets', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_end_date'), table_name='markets')
    op.drop_column('markets', 'end_date')
    # ### end Alembic commands ###

