"""Add contact_number to users

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('contact_number', sa.String(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET contact_number = '+630000000000' WHERE contact_number IS NULL")
    # Now make it non-nullable
    op.alter_column('users', 'contact_number', nullable=False)
    op.create_index(op.f('ix_users_contact_number'), 'users', ['contact_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_contact_number'), table_name='users')
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###

