"""Create resolutions table

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-01-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=False),
    sa.Column('evidence_urls', sa.JSON(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolutions_id'), 'resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_resolutions_market_id'), 'resolutions', ['market_id'], unique=True)
    op.create_index(op.f('ix_resolutions_outcome_id'), 'resolutions', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_resolutions_resolved_by'), 'resolutions', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_resolutions_created_at'), 'resolutions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolutions_created_at'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_resolved_by'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_outcome_id'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_market_id'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_id'), table_name='resolutions')
    op.drop_table('resolutions')
    # ### end Alembic commands ###

