"""Add badges to users and create reputation_history table

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-01-06 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add badges column to users table
    op.add_column('users', sa.Column('badges', sa.JSON(), nullable=True))
    
    # Create reputation_history table
    op.create_table('reputation_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('total_forecast_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_history_id'), 'reputation_history', ['id'], unique=False)
    op.create_index(op.f('ix_reputation_history_user_id'), 'reputation_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_reputation_history_created_at'), 'reputation_history', ['created_at'], unique=False)
    op.create_index('ix_reputation_history_user_created', 'reputation_history', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reputation_history_user_created', table_name='reputation_history')
    op.drop_index(op.f('ix_reputation_history_created_at'), table_name='reputation_history')
    op.drop_index(op.f('ix_reputation_history_user_id'), table_name='reputation_history')
    op.drop_index(op.f('ix_reputation_history_id'), table_name='reputation_history')
    op.drop_table('reputation_history')
    op.drop_column('users', 'badges')
    # ### end Alembic commands ###

