"""Add streaks to users

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-01-06 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add streak columns to users table
    op.add_column('users', sa.Column('winning_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('activity_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_streak')
    op.drop_column('users', 'winning_streak')
    # ### end Alembic commands ###

